pipeline {
    agent any
    triggers { pollSCM('* * * * *') }
    stages {
        stage('Terraform apply') {
            steps {
                sh '''
                    cd ./openmrs
                    terraform init
                    terraform validate
                    terraform apply -auto-approve -var="web_pass=Password@1234" -var="trigger=${BUILD_NUMBER}"
                '''
            }
        }
    }
}