---
- name: Deploy Spring Pet Clinic
  hosts: localhost
  become: yes
  tasks:
  - name: Update Packages
    ansible.builtin.apt:
      pkg: 
      - openjdk-11-jdk
      - maven
      state: present
      
