---
- name: Deploy Spring Pet Clinic
  hosts: localhost
  tasks:
  - name: Update Packages
    ansible.builtin.apt:
      pkg: 
      - openjdk-11-jdk
      - maven
      state: latest
      update_cache: yes