---
- name: Update Packages
  hosts: localhost
  become: yes
  tasks:
  - name: Update Packages
    ansible.builtin.apt:
      pkg: 
      - software-properties-common
      state: present
      update_cache: yes
  - name: Apt Repository
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
  - name: Install Python 3.9
    ansible.builtin.apt:
      pkg: 
        - python3.9
        - python3-pip
        - python3-flask
      state: present
  - name: Cloning git repository
    ansible.builtin.git:
      repo: 'https://github.com/Sysnove/flask-hello-world.git'
      dest: /home/flask/flask-hello-world
      clone: yes
  - name: Move hello.py to app.py
    ansible.builtin.copy:
      src: /home/flask/flask-hello-world/hello.py
      dest: /home/flask/flask-hello-world/app.py
      backup: yes
  - name: Copy Service File
    ansible.builtin.copy:
      src: /home/flask/flask.service
      dest: /etc/systemd/system/flask.service
  - name: Deamon Reload
    ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: flask