---
- name: Update Packages
  hosts: localhost
  become: yes
  tasks:
  - name: Update Packages
    ansible.builtin.apt:
      pkg: 
      - software-properties-common
      state: present
      update_cache: yes
  - name: Apt Repository
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
  - name: Install Python 3.9
    ansible.builtin.apt:
      pkg: 
        - python3.9
        - python3-pip
        - python3-flask
      state: present